version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: username  
      MONGO_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    ports:
      - 27017:27017
    networks: 
     - network-backend

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo 
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin 
    networks:
      - network-backend   

networks:
  network-backend:

volumes: 
  mongodb_data:
